/*
 * The Capgemini Movie Database
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MovieRatings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-22T22:28:01.142+02:00")
public class MovieRatings {
  @SerializedName("criticsScore")
  private Integer criticsScore = null;

  @SerializedName("audienceScore")
  private Integer audienceScore = null;

  public MovieRatings criticsScore(Integer criticsScore) {
    this.criticsScore = criticsScore;
    return this;
  }

   /**
   * Get criticsScore
   * minimum: 0
   * maximum: 100
   * @return criticsScore
  **/
  @ApiModelProperty(value = "")
  public Integer getCriticsScore() {
    return criticsScore;
  }

  public void setCriticsScore(Integer criticsScore) {
    this.criticsScore = criticsScore;
  }

  public MovieRatings audienceScore(Integer audienceScore) {
    this.audienceScore = audienceScore;
    return this;
  }

   /**
   * Get audienceScore
   * minimum: 0
   * maximum: 100
   * @return audienceScore
  **/
  @ApiModelProperty(value = "")
  public Integer getAudienceScore() {
    return audienceScore;
  }

  public void setAudienceScore(Integer audienceScore) {
    this.audienceScore = audienceScore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieRatings movieRatings = (MovieRatings) o;
    return Objects.equals(this.criticsScore, movieRatings.criticsScore) &&
        Objects.equals(this.audienceScore, movieRatings.audienceScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(criticsScore, audienceScore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieRatings {\n");
    
    sb.append("    criticsScore: ").append(toIndentedString(criticsScore)).append("\n");
    sb.append("    audienceScore: ").append(toIndentedString(audienceScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

